### ISSUE TITLE
Unable to access the lab1 cart

### ISSUE THREAD

**Issue by 007divyachawla** [BishopFox/json-interop-vuln-labs#1]
## Description of Bug
After running the command docker-compose up --build, the lab is been created but on accessing the 127.0.0.1:5000, its gives 404 Error.
## What should the expected behavior be
Should be able to access the lab.
## Platform Affected
[ ] Dev
[ ] Preview
[ ] Production

## Steps to Reproduce
Steps to reproduce the behavior

### Additional context
OS, Desktop/Mobile, Browser, Date/Time,

**Comment by the-bumble** [comment]
Hi @007divyachawla,

There is nothing hosted on the "/" endpoint, which is why there is a 404. Follow the instructions in the [Lab1](https://github.com/BishopFox/json-interop-vuln-labs/blob/master/lab1/README.md) and [Lab2](https://github.com/BishopFox/json-interop-vuln-labs/blob/master/lab2/README.md) readmes.

Hope that helps! Thank you for checking it out!

Jake
